package com.gx.htgl.dao;

import com.gx.htgl.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2022-02-10 09:17:26
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2022-02-10 09:17:26
     */
    int insertSelective(User record);
}